<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNdhhjyz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNdhhjyz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNdhhjyz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNdhhjyz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNdhhjyz\appProdProjectContainer([
    'container.build_hash' => 'Ndhhjyz',
    'container.build_id' => '881a22c3',
    'container.build_time' => 1627455441,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNdhhjyz');
