<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOocftk5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOocftk5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOocftk5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOocftk5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOocftk5\appProdProjectContainer([
    'container.build_hash' => 'Oocftk5',
    'container.build_id' => '1f3789b0',
    'container.build_time' => 1627380129,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOocftk5');
